# Generated by Django 5.1.6 on 2025-03-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_data", "0002_geo_data_ip_init"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_init", models.CharField(max_length=50, null=True)),
                ("ip_range", models.BigIntegerField()),
                ("country", models.CharField(max_length=50)),
                ("country_code", models.CharField(max_length=5)),
                ("region", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("Timezone", models.TimeField()),
                ("local_time", models.DateTimeField()),
                ("latitude", models.IntegerField()),
                ("longitude", models.IntegerField()),
                ("zip_code", models.IntegerField()),
                ("asn", models.CharField(max_length=100)),
                ("isp", models.IntegerField()),
                ("domain", models.CharField(max_length=100)),
                ("usage_type", models.CharField(max_length=250)),
                ("last_seen", models.CharField(max_length=100)),
                ("threat", models.CharField(max_length=100)),
                ("residential", models.CharField(max_length=250)),
                ("provider", models.CharField(max_length=200)),
                ("fraudscore", models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name="geo_data",
        ),
    ]
