# Generated by Django 5.1.6 on 2025-03-18 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo_data", "0003_geodata_delete_geo_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GeoData",
        ),
    ]
