# Generated by Django 5.1.6 on 2025-03-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="geo_data",
            name="ip_init",
            field=models.BigIntegerField(null=True),
        ),
    ]
